### ISSUE TITLE
Throws error on running 

### ISSUE THREAD

**Issue by Gamerz261** [cheesits456/discord-ssh-bot#7] opened 2020-10-31 22:54 UTC
Whenever you use the command specified in the readme (node index.js) the application throws the following error:

![2020-10-31](https://user-images.githubusercontent.com/52172630/97791585-0bb51200-1ba2-11eb-99f5-4d9f1055b7e9.png)

**Comment by cheesits456** [comment] 2020-11-01 06:24
this might be related to discord's recent API changes, i'll look into this tonight and try to get it functional again

**Comment by Gamerz261** [comment] 2020-11-01 19:42
Sorry I only just saw this, apparently GitHub doesn't like sending notifications anymore, but thank you for looking into this issue, please let me know if you fix it :D

**Comment by cheesits456** [comment] 2020-11-03 13:29
Would you be able to provide more information about your system and configuration?
I've tried multiple configurations across different platcroms and all have worked perfectly fine, i can't seem to be able to rproduce this error

**Comment by Gamerz261** [comment] 2020-11-04 19:39
Yes, I'm running this program on an old Linux Ubuntu system with an intel dual core (ik... I said it was old lmao)

**Comment by cheesits456** [comment] 2020-11-05 17:44
what version of nodejs are you running, and could you provide the contents of your config.json file, with the token censored out of course

**Comment by Gamerz261** [comment] 2020-11-08 19:09
sorry for not seeing this but in the config, I'm running
{
        "channel": "772217287226294302",
        "owner": "",
        "token": "<redacted>"
}
and I'm running on NodeJS 14.0

**Comment by cheesits456** [comment] 2020-11-14 03:35
Sorry for such a delayed response - I'm still unable to reproduce your issue, so there's not much I can do to try to find the cause. I'm not sure why this issue occurred for you

**Comment by Gamerz261** [comment] 2020-11-15 23:54
Ok, I'll try some stuff on my end to see if I can reproduce the problem. Just out of curiosity, what is your suggested memory size (for when I run the command) I'm using -1024 which should be more than enough.

**Comment by Gamerz261** [comment] 2020-11-15 23:54
Also in the config, the owner i wasn't sure exactly what to put there

**Comment by cheesits456** [comment] 2020-11-19 10:53
Ahhhhh okay yeah that's probably the source of the error - for the `owner` key in `config.json`, you need to put your Discord user ID

**Comment by Gamerz261** [comment] 2020-11-19 14:55
Ok I'll check later today

**Comment by Gamerz261** [comment] 2020-12-12 23:20
sorry for coming back to this so late, but I have realized the OS flag in packages.json should _probably_ be changed because I am running this bot on Ubuntu Linux

**Comment by cheesits456** [comment] 2020-12-13 08:10
`!win32` means any OS aside from `win32` - `!` means `not`

**Comment by MikkelDK** [comment] 2020-12-20 16:02
Hey.

I have same issues when starting the index.js :) any fix planned?

**Comment by cheesits456** [comment] 2020-12-20 18:09
Found the source of the problem - the bot was trying to grab the owner's user object by using `client.users.cache.get(id)`, but with Discord's relatively recent API changes, user objects don't get cached automatically anymore unless you specifically flip the switch in the Discord developer panel to turn that on. I've swapped out the old function call in favor of `client.users.fetch(id)` and can confirm it is now fully working as intended :)

**Comment by cheesits456** [comment] 2020-12-20 18:10
Resolved in 11a41cef2c6e99168c1bd26dd1d38993629180d3

**Closed by cheesits456** 2020-12-20 18:10 UTC
Labels: bug
